apiVersion: v1
kind: LimitRange
metadata:
  name: gpu-limit-range
  namespace: inferex
spec:
  limits:
    - type: Container
      default:
        nvidia.com/gpu: "1"
      defaultRequest:
        nvidia.com/gpu: "1"
